### ISSUE TITLE
samples/ folder?

### ISSUE THREAD

**Issue by gliptak** [VeerMuchandi/istio-on-openshift#1]
The notes reference files in ```samples/```. Please add those files to the repo. Thanks

**Comment by VeerMuchandi** [comment]
When you download Istio as explained here
https://github.com/VeerMuchandi/istio-on-openshift/blob/master/DeployingIstioWithOcclusterup.md#download-istio

samples are also downloaded. Sorry if that was not clear!!

**Comment by gliptak** [comment]
Thank you
